"use client";

import { useCallback } from "react";
import type { WeatherCondition } from "@/components/tool-ui/weather-widget/schema";
import type { ConditionOverrides } from "../../weather-compositor/presets";
import { WEATHER_CONDITIONS } from "../../weather-compositor/presets";

type ExportFormat = "json-overrides" | "json-full" | "typescript";

interface ExportOptions {
  format: ExportFormat;
  conditions?: WeatherCondition[];
  includeMetadata?: boolean;
}

export function useCodeGen(
  overrides: Partial<Record<WeatherCondition, ConditionOverrides>>,
  signedOff: Set<WeatherCondition>
) {
  const generateJson = useCallback(
    (options: ExportOptions): string => {
      const conditionsToExport =
        options.conditions ?? WEATHER_CONDITIONS.filter((c) => overrides[c]);

      const data: Record<string, unknown> = {};

      if (options.includeMetadata) {
        data.exportedAt = new Date().toISOString();
        data.signedOff = Array.from(signedOff);
      }

      data.overrides = {};
      for (const condition of conditionsToExport) {
        if (overrides[condition]) {
          (data.overrides as Record<string, ConditionOverrides>)[condition] =
            overrides[condition]!;
        }
      }

      return JSON.stringify(data, null, 2);
    },
    [overrides, signedOff]
  );

  const generateTypeScript = useCallback((): string => {
    const lines: string[] = [
      "// Generated by Weather Tuning Studio",
      `// Exported at: ${new Date().toISOString()}`,
      "",
      "import type { ConditionOverrides } from './presets';",
      "import type { WeatherCondition } from '@/components/tool-ui/weather-widget/schema';",
      "",
      "export const TUNED_OVERRIDES: Partial<Record<WeatherCondition, ConditionOverrides>> = {",
    ];

    for (const condition of WEATHER_CONDITIONS) {
      const conditionOverrides = overrides[condition];
      if (!conditionOverrides) continue;

      const isSignedOff = signedOff.has(condition);
      lines.push(`  // ${condition}${isSignedOff ? " ✓ signed off" : ""}`);
      lines.push(`  "${condition}": {`);

      if (conditionOverrides.layers) {
        lines.push("    layers: {");
        for (const [key, value] of Object.entries(conditionOverrides.layers)) {
          lines.push(`      ${key}: ${JSON.stringify(value)},`);
        }
        lines.push("    },");
      }

      if (conditionOverrides.celestial) {
        lines.push("    celestial: {");
        for (const [key, value] of Object.entries(conditionOverrides.celestial)) {
          lines.push(`      ${key}: ${typeof value === "number" ? value.toFixed(4) : JSON.stringify(value)},`);
        }
        lines.push("    },");
      }

      if (conditionOverrides.cloud) {
        lines.push("    cloud: {");
        for (const [key, value] of Object.entries(conditionOverrides.cloud)) {
          lines.push(`      ${key}: ${typeof value === "number" ? value.toFixed(4) : JSON.stringify(value)},`);
        }
        lines.push("    },");
      }

      if (conditionOverrides.rain) {
        lines.push("    rain: {");
        for (const [key, value] of Object.entries(conditionOverrides.rain)) {
          lines.push(`      ${key}: ${typeof value === "number" ? value.toFixed(4) : JSON.stringify(value)},`);
        }
        lines.push("    },");
      }

      if (conditionOverrides.lightning) {
        lines.push("    lightning: {");
        for (const [key, value] of Object.entries(conditionOverrides.lightning)) {
          lines.push(`      ${key}: ${typeof value === "number" ? value.toFixed(4) : JSON.stringify(value)},`);
        }
        lines.push("    },");
      }

      if (conditionOverrides.snow) {
        lines.push("    snow: {");
        for (const [key, value] of Object.entries(conditionOverrides.snow)) {
          lines.push(`      ${key}: ${typeof value === "number" ? value.toFixed(4) : JSON.stringify(value)},`);
        }
        lines.push("    },");
      }

      lines.push("  },");
    }

    lines.push("};");
    lines.push("");

    return lines.join("\n");
  }, [overrides, signedOff]);

  const copyToClipboard = useCallback(
    async (options: ExportOptions): Promise<void> => {
      let content: string;

      if (options.format === "typescript") {
        content = generateTypeScript();
      } else {
        content = generateJson(options);
      }

      await navigator.clipboard.writeText(content);
    },
    [generateJson, generateTypeScript]
  );

  const downloadFile = useCallback(
    (options: ExportOptions): void => {
      let content: string;
      let filename: string;
      let mimeType: string;

      if (options.format === "typescript") {
        content = generateTypeScript();
        filename = "tuned-overrides.ts";
        mimeType = "text/typescript";
      } else {
        content = generateJson(options);
        filename = "weather-tuning-export.json";
        mimeType = "application/json";
      }

      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
    },
    [generateJson, generateTypeScript]
  );

  return {
    generateJson,
    generateTypeScript,
    copyToClipboard,
    downloadFile,
  };
}
